import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import Provider from "@/components/provider/Provider";

export const metadata = {
    title: "Judicial Ease- AI Research Engine For Commercial Court",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                {/* Add your custom favicon here */}
                <link rel="icon" href="/logo-1.png" sizes="any" type="image/x-icon" />
            </head>
            <body className={inter.className}>
                <Provider>{children}</Provider>
            </body>
        </html>
    );
}
